### ISSUE TITLE
Code keeps throwing error

### ISSUE THREAD

**Issue by vghfr** [ammezie/webcage#1]
```
Error: Cannot find module './helpers/formatDate'
Require stack:
- /home/runner/hoot/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at /home/runner/hoot/index.js:5:23
    at Script.runInContext (vm.js:130:18)
    at Object.<anonymous> (/run_dir/interp.js:209:20)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
```
I have not edited any code.

**Comment by vghfr** [comment]
Whoops, completely overlooked the helpers
